### ISSUE TITLE
alpinejs v3 

### ISSUE THREAD

**Issue by jet10000** [MrBin99/django-vite-example#3]
![image](https://user-images.githubusercontent.com/2258120/145702742-9a7e2197-ae1d-4681-bb69-c954a44876c6.png)
![image](https://user-images.githubusercontent.com/2258120/145702755-f4a7aefc-3cea-4a5b-9cb3-a8c19e22a923.png)
![image](https://user-images.githubusercontent.com/2258120/145702765-041c35b4-5f79-45d3-8778-54899dcaf119.png)
![image](https://user-images.githubusercontent.com/2258120/145702772-3a9e1517-c2e4-4bf6-92fb-cb3e819de215.png)
![image](https://user-images.githubusercontent.com/2258120/145702780-fda69063-0924-41a3-b9e9-f50d4d224e22.png)
![image](https://user-images.githubusercontent.com/2258120/145702791-386bd82b-11f1-400a-8c8f-af8fbd64437d.png)

**Comment by MrBin99** [comment]
I'm sorry but if you don't provide any context on your bug and just throw screenshots of stacktraces. This will not encourage
people to help you.

**Comment by jet10000** [comment]
I have found the problem, but it can't be solved. Currently django-vite only supports alpinejs v2, not alpinejs v3. I changed the build target to es2017, but it still doesn't solve it.

https://github.com/alpinejs/alpine/discussions/2487#discussioncomment-1792606

**Comment by MrBin99** [comment]
Your problem is more à JS problem than a Python problem. It is maybe ViteJS that is not compatible with AlpineJS v3 ?
